### ISSUE TITLE
Figures should be in folder structure

### ISSUE THREAD

**Issue by jd4900** [OpenChemE/CHBE220-OER-Dev#2]
Instead of leaving images in lecture file they should be in an `img` (or graphics,  folder in the home directory as typical in Python projects or website structures. This will make things easier in the long run - especially if you reuse images in later notebooks as well as make the repo more readable. 

The following hierarchy is proposed:

```
figs/
--lecture1/
----fig1.png
----fig2.png
--lecture2/
----fig1.png
----fig2.png
Lecture1/
Lecture2/
```

or you could do: 

```
Lecture1/
--figs/
----fig1.png
----fig2.png
Lecture2/
--figs/
----fig1.png
----fig2.png
```

The architecture is up to you!

**Comment by jverrett** [comment]
Thanks Josh for this suggestion. We'll likely go with format 2 that you suggest since we don't anticipate too many duplications in images.
